# Generated by Django 4.2.4 on 2023-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
